name: Gitlab-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  image_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: docker://alpine:3.8
    - name: building docker image with the commit SHA ${{GITHUB_SHA}}
      run: docker built -t ${{GITHUB_SHA}} .
    #- name: Setup Heroku
    #  uses: actions/heroku@main
    #- name: test heroku
    #  run: heroku -h
