name: Gitlab-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  image_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Heroku environment
      with:
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      uses: actions/heroku@main
    - name: Get heroku long token
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: | 
        heroku authorizations:create,
        heroku container:push web -a ${{ secrets.HEROKU_APP }}
      
      
#     - uses: docker://alpine:3.8
#     - name: building docker image with the commit SHA $GITHUB_SHA
#       run: docker build -t $GITHUB_SHA .
